name: Test package

on:
  - push

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4' 

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        # Run tests with sudo, since some commands need to sniff for network access
        # and require root access
        run: |
          sudo poetry run pytest proxy_benchmarks
