name: Test package

on:
  - push

jobs:
  test-python:
    name: Test python
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install go dependencies
        run: cd groove && ./setup.sh && ./build.sh

      - name: Install python
        run: cd groove/groove-python && poetry install

      - name: Run tests
        run: cd groove/groove-python && poetry run pytest groove
