name: Test groove

on:
  push:
    paths:
      - 'groove/**/*'
      - '.github/workflows/*groove.*'

env:
  IMAGE: piercefreeman/proxy-benchmarks

jobs:
  build:
    name: Build groove base
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: groove/groove.Dockerfile
          context: groove
          push: true
          tags: ${{ env.IMAGE }}:groove-${{ github.sha }}

  run_tests:
    name: Run groove-python tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE }}:groove-${{ github.sha }}

      - name: Run test
        run:
          docker run ${{ env.IMAGE }}:groove-${{ github.sha }} test-python

  publish:
    name: Run groove-python tests
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE }}:groove-${{ github.sha }}

      - name: Publish test
        run:
          docker run ${{ env.IMAGE }}:groove-${{ github.sha }} deploy-python --env PYPI_USERNAME=${{ secrets.PYPI_USERNAME }} --env PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
